name: TheCollection
favicon: null
layout_spectrum: 0.22181511530652642
typography_spectrum: 0.15082656755112112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.30723989964462817
  lightness: 0.5014825535472482
  saturation: 0.7707742031197995
  rhythmicContrast: 0.07079142075963318
purpose: []
